### ISSUE TITLE
Check for redirects

### ISSUE THREAD

**Issue by danielroe** [danielroe/page-speed.dev#9]
To subdomain or path...

https://x.com/tunetheweb/status/1756229370752942099

**Comment by moshetanzer** [comment]
Can I have a bash at this? Any guidance? Should it be done in utils?

**Comment by danielroe** [comment]
we could do this as a preliminary step in the server handlers - basically just fetch the domain, check if a redirect is set or anything but a 200 is sent back.

we then need to handle the redirect (= redirect to the new domain on page-speed.dev) and also handle non-200 responses (= show a user-friendly error message)

**Comment by moshetanzer** [comment]
Hi @danielroe,

- shouldnt it be done once for both run and crux - same domain (unless i misunderstood you)?
- was thinking to keep it simple one of two options
  - oftenn redirect is just going to be https://www.example.com instead of https://example.com - which i dont think we should chnage the url for rather instead just put a little message undernetaht the field stating "Final url tested was finalUrl" like pagespeed.dev does? we could do a chceck to see if base domain name has changed and then redirect? else mostly the url that a person enters does correlate to the site they want to test and thus just for everything put a message of which domain was tested instead of redirecting.
  
What are your thoughts?

**Comment by moshetanzer** [comment]
@danielroe any thought on the linked PR?
